from geoalchemy2 import Geometry
from sqlalchemy import Column, Integer, String, Float, Index
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class BaseCarModel(Base):
    __tablename__ = "base_car"
    __table_args__ = (
        {"schema": "agroprods"},
    )

    # Chave primária gerada por identidade (GENERATED BY DEFAULT AS IDENTITY)
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Mapeamento dos campos TEXT e FLOAT8
    cod_tema = Column(String, nullable=True)
    nom_tema = Column(String, nullable=True)
    cod_imovel = Column(String, nullable=True)
    num_area = Column(Float, nullable=True)
    ind_status = Column(String, nullable=True)
    des_condic = Column(String, nullable=True)

    # Campo espacial com SRID 4674 e tipo genérico GEOMETRY
    # O GeoAlchemy2 gerencia internamente a criação do índice GIST padrão
    geometry = Column(Geometry(geometry_type='GEOMETRY', srid=4674), nullable=True)

# Definição explícita dos índices GIST adicionais solicitados no seu script SQL
Index("base_car_geo_idx", BaseCarModel.geometry, postgresql_using="gist")
Index("idx_base_car_geometry", BaseCarModel.geometry, postgresql_using="gist")
