name: deploy-processamento

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/processamento-api:latest
          # 1. REMOVIDO O CACHE GHA PARA FORÇAR A INSTALAÇÃO DO ASYNCPG/RASTERIO/GEOALCHEMY

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2214
          script: |
            mkdir -p ~/develop/proc-api
            cd ~/develop/proc-api
            echo "${{ secrets.ENV_FILE }}" > .env
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            cd ~/develop
            docker network inspect traefik-network >/dev/null 2>&1 || docker network create traefik-network
            
            # 2. COMANDO CORRIGIDO: apontando para o serviço correto 'api-python-rest'
            docker compose -f docker-compose-deploy.yml pull api-python-rest
            
            # 3. FORÇA A RECRIAÇÃO DOS CONTÊINERES COM A IMAGEM NOVA
            docker compose -f docker-compose-deploy.yml up -d --force-recreate --remove-orphans
